# Generated by Django 3.0.8 on 2020-07-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Name')),
                ('number', models.IntegerField(default=0, verbose_name='Number')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is main?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons_images', verbose_name='Image')),
                ('name_slug', models.CharField(blank=True, max_length=250, verbose_name='Name slug')),
                ('sale', models.CharField(blank=True, max_length=50, verbose_name='sale')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Course')),
            ],
        ),
    ]
