# Generated by Django 3.0.8 on 2020-07-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='sale',
            field=models.CharField(blank=True, max_length=150, verbose_name='sale'),
        ),
    ]
