# Generated by Django 3.0.8 on 2020-09-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200724_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='is top'),
        ),
    ]
