DATA_DIR = '/Users/mac/PycharmProjects/REAL_TIME_INK/data'
VIDEO_DIR = '/Users/mac/video'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'INSERT_PROVIDED_KEY_HERE'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'INSERT_PROVIDED_SECRET_HERE'